resgf_status <- setClass("resgf_status",
                         list(local.db.dir="character",
                              remote.manifest="resgf_manifest",
                              checksums.verified="logical",
                              status="data.frame"))

setMethod("show",signature(object="resgf_status"),
          function(object) {
            cat(sprintf("%-30s : %s\n","Local directory",object@local.db.dir))
            cat(sprintf("%-30s : %i\n","Local files",sum(!is.na(object@status$local.path))))
            cat(sprintf("%-30s : %s\n","Checksums verified?",object@checksums.verified))
            cat(sprintf("%-30s : %i\n","Remote files",nrow(object@remote.manifest@manifest)))
            cat(sprintf("%-30s : %i\n","Remote files locally valid",
                        sum(object@status$locally.valid & object@status$in.manifest)))
            cat(sprintf("%-30s : %i\n","Invalid/missing locally",
                        sum(!object@status$locally.valid & object@status$in.manifest)))
          })

#' Summarise status  
#' 
#' Summarise the results stored in a resgf_status object in terms of one of the filename fields or the data node
#'
#' @param object An resgf_status object
#' @param field.idx Index of the filename field to summarise over.
#' @param field.sep  Character used to separate fields in the filename. Default is "_"
#' @return A tibble summarising the status accordingly.
#' @name summariseStatus
#' @export
#'
resgf_status_by_field <- function(object,field.idx=1,field.sep="_") {
  #Check inputs
  assert_that(is(object,"resgf_status"),
              msg="Supplied object is not an resgf_status object")
  assert_that(length(field.idx)==1,
              msg="Field argument must be an integer of length 1")
  
  #Split filenames into fiels
  this.status <- 
    object@status %>%
    filter(in.manifest) %>%
    mutate(noext.fname=gsub("\\..*?$","",filename),
           field=str_split(noext.fname,field.sep,simplify = TRUE))
  
  #Check that request is ok
  assert_that(ncol(this.status$field) >= field.idx,
              msg=sprintf("Field index requested, %i, is too high. Max value is %i.",field.idx,ncol(this.status$field)))
  
  this.status %>%
    mutate(field.value=field[,field.idx]) %>%
    group_by(field.value) %>%
    summarise(remote.files=n(),
              local.files=sum(locally.valid),
              proportion=mean(locally.valid))
}

#' @export
#' @name summariseStatus
resgf_status_by_node <- function(object) {
  assert_that(is(object,"resgf_status"),
              msg="Supplied object is not an resgf_status object")
  object@status %>%
    filter(in.manifest) %>%
    extract(url,"data.node","^(https*://.*?)/.*$",remove=FALSE) %>%
    group_by(data.node) %>%
    summarise(remote.files=n(),
              local.files=sum(locally.valid),
              proportion=mean(locally.valid))
  
}

#' Compare local database with ESGF search
#'
#' Compares the list of files ("manifest") generated by an ESGF search with the locally downloaded files
#'
#' @param local.db.dir Path to the local directory. Files nested in subdirectories are also detected.
#' @param esgf.manifest resgf_manifest object generated previously, which forms the reference database
#' @param check.checksums Should the comparison be done using the checksums (slow!)? Or only the filenames.
#'
#' @return An resgf_status object
#' @export
#'
#' @examples
#' resgf_check_status(local.db.dir=pwd(),
#'                    esgf.manifest=this.manifest)
resgf_status_check <-
  function(local.db.dir,
           esgf.manifest,
           check.checksums=FALSE) {

  #Setup status object
  this.status <- resgf_status(local.db.dir=local.db.dir,
                              remote.manifest=esgf.manifest,
                              checksums.verified=check.checksums)

  #Get list of files already existing in database
  local.db <-
    tibble(local.path=dir(local.db.dir,full.names=TRUE,pattern="*.nc",recursive=TRUE)) %>%
    mutate(filename=basename(local.path))

  #Merge with manifest
  status.db <- full_join(esgf.manifest@manifest,local.db,by="filename")

  #Here we would do the checksum check
  status.db <-
    mutate(status.db,
           locally.valid=!is.na(local.path),
           in.manifest=!is.na(url))

  this.status@status <- status.db

  return(this.status)
  }

